[package]
name = "regalloc_common"
version = "0.1.0"
edition = "2024"

[dependencies]
alyn_common = { path = "../alyn_common" }
derive_more = { version = "2.0.1", features = [
    "from", "try_from", "debug", "display", "add", "into"
] }
